# Generated by Django 5.0.7 on 2024-07-19 15:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='content',
        ),
        migrations.AddField(
            model_name='resources',
            name='content_one',
            field=models.TextField(default='Default content for content one'),
        ),
        migrations.AddField(
            model_name='resources',
            name='content_one_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='resources',
            name='content_three',
            field=models.TextField(default='Default content for content three'),
        ),
        migrations.AddField(
            model_name='resources',
            name='content_three_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='resources',
            name='content_two',
            field=models.TextField(default='Default content for content two'),
        ),
        migrations.AddField(
            model_name='resources',
            name='content_two_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
