# Generated by Django 5.0.7 on 2024-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='content',
        ),
        migrations.AddField(
            model_name='resources',
            name='content_one',
            field=models.TextField(default='Default content for content one'),
        ),
        migrations.AddField(
            model_name='resources',
            name='content_three',
            field=models.TextField(default='Default content for content three'),
        ),
        migrations.AddField(
            model_name='resources',
            name='content_two',
            field=models.TextField(default='Default content for content two'),
        ),
    ]
